# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3c3722f9d472222587d0db643e7f163f9a325d01b861debc583e33adc4602a4f5c98e9ae8281631d2373649665f4676e6a35707146901947c40c5efe5bd00018

test:
  secret_key_base: 91a761edfbd66558ea936bb6a136071fd64cd3ddaa9baaba1254587b9d186f6524a1f1574ca0c9e63a998faca740afddf2a4dd05bac500314534201a07e5d149

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
